POST http://localhost:4000/item
Content-Type: application/json

[
  {
    "name": "Flexi Dumbell",
    "imgUrl": "imgs/flexidumbell.webp",
    "amount": 560
  },
  {
    "name": "Flexi Bike",
    "imgUrl": "imgs/BikeMain_1260x.webp",
    "amount": 960
  },
  {
    "name": "Flexi Kettle",
    "imgUrl": "imgs/flexiKettle.webp",
    "amount": 240
  },
  {
    "name": "Treadmill",
    "imgUrl": "imgs/flextread_img00_1260x.webp",
    "amount": 3000
  }
]

###
GET http://localhost:4000/item

###
DELETE  http://localhost:4000/item

###
POST http://localhost:4000/order
Content-Type: application/json

{
  "name": "prash",
  "email": "prash@gmail.com",
  "shipping": "address",
  "orders": [{
    "_id": "63d50d0f525044993117f991",
    "quantity": 2
  },
  {
    "_id": "63d50d0f525044993117f992",
    "quantity": 2
  }]
}

###
GET http://localhost:4000/order